version: '3'

services:
  web:
    build: .
    image: medensao/web:latest
    command: sh -c "  python3 manage.py makemigrations 
            && python manage.py migrate 
            && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    #image: medensa/web:latest
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
